### ISSUE TITLE
App not syncing 

### ISSUE THREAD

**Issue by Tusker13-04** [GDGVIT/vitty-app#30]
I have uploaded my timetable on website, but  it is not getting reflected on phone after app update

**Comment by Tusker13-04** [comment]
Course code is being shown instead of subject name 
And
The two slots of lab class are shown as two separate elements instead of one

**Comment by dk-a-dev** [comment]
@Tusker13-04 I hope your first issue is resolved and the time table is now accesible
for ur second query(of two lab slots) we will resolve that in future updates ♥

**Comment by Tusker13-04** [comment]
i am still seeing course code instead of course name on the app.
the vitty website is showing the correct course name , but the phone is still showing course code

**Comment by dk-a-dev** [comment]
issue resolved as of now
