### ISSUE TITLE
Upload/Edit Timetable does not work on Firefox

### ISSUE THREAD

**Issue by IM-TechieScientist** [GDGVIT/vitty-app#33]
**Describe the bug**
I get the following error while trying to upload/edit my timetable from vtop on firefox. It works perfectly fine on chrome and other chromium based browsers.

![image](https://github.com/user-attachments/assets/247412bb-ba11-4d68-b942-1dc2f1bec73a)

**To Reproduce**
1. Use Firefox browser to copy and paste timetable from vtop.

**Comment by PavitranVC** [comment]
Same dude. I cannot update my timetable from firefox. I tried with other chromium based browsers, it worked

**Comment by dk-a-dev** [comment]
Thanks for the info 
will check on this

**Comment by dk-a-dev** [comment]
This error is from parser, it throws wrong format errro and fe responses like this
This issue is resolved in upcoming version of app VITTY-3.0

**Comment by TechPro424** [comment]
@dk-a-dev I'm still facing this problem on latest version of chrome
